### PR TITLE
Registration decorator

### PR DESCRIPTION
**Pull request by rob-smallshire**
This example below illustrates how I'd like to be able to use docopt_subcommands.  To this end, this PR adds a `register()` function decorator as a method to `Subcommands`.

```
"""{program} - Interrogation of SEG Y seismic data.

Usage: {program} [options] <command> [<args> ...]

Options:
  -h --help          Show this screen.
  --log-level=LEVEL  Use verbose logging

Commands:
  {available_commands}

See '{program} help <command>' for help on specific commands.
"""

import json

import segpy
import sys

from docopt_subcommands import Subcommands

from segpy.reader import create_reader

commands = Subcommands(program='segpy',
                       version='segpy-{}'.format(segpy.__version__),
                       doc_template=__doc__,
                       common_option_handler=None)


@commands.register('metadata')
def handle_metadata(args):
    """usage: {program} {command} <filename>

    Print metadata for a SEGY file.
    """

    result = {}

    filename = args['<filename>']
    with open(filename, 'rb') as fh:
        reader = create_reader(fh)
        result['num_traces'] = reader.num_traces()
        result['dimensionality'] = reader.dimensionality
        result['data_sample_format'] = reader.data_sample_format
        result['max_num_trace_samples'] = reader.max_num_trace_samples()

    print(json.dumps(result))


def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]
    commands(argv)

__doc__ = commands.top_level_doc
```

### CODE REVIEW

**Comment by abingham** [comment]
How is this different from the `Subcommands.command` decorator?

**Comment by rob-smallshire** [comment]
Chiefly because I know about this one!

Bugger.

**Comment by abingham** [comment]
Sorry about that. The README could probably use some TLC. I've got some examples of "advanced" usage in the `examples` directory, but an up-front blurb about using your own `Subcommands` instance would probably be helpful.

**Comment by abingham** [comment]
FWIW, your implementation is almost a verbatim copy of mine...great minds!

**Pull request closed without merging**
